services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
      - default
    ports:
     - "3000:3000" 
    env_file: $DOCKERDIR/.env
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
      - /data:/mnt/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
