services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - /data/downloads:/data/downloads
    restart: unless-stopped
    depends_on:
      - gluetun