services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - /data:/data
    restart: unless-stopped
    depends_on:
      - gluetun